### ISSUE TITLE
Bug :: An attempt was made to load an assembly from a network location

### ISSUE THREAD

**Issue by MahdiForoughi** [YODevs/YO#100]
Complete Error Detail : 
An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information

**Comment by YODevs** [comment]
-     Right Click 'YOCA.exe'
-     Click Properties
-     Click Unblock

![image](https://user-images.githubusercontent.com/53114901/116997648-500ca080-acf2-11eb-8879-7c0d33bed97f.png)

**Comment by YODevs** [comment]
Modified output file by `YOCA.exe.config`
Thanks for letting me know about this issue and for help fixing it.
