### ISSUE TITLE
Feature :: Setting required condition to function arguments

### ISSUE THREAD

**Issue by MahdiForoughi** [YODevs/YO#128]
I believe this feature as an easy way to managing function arguments with a simple statement or etc... that can help us to switch from boring nested **if-else** statements in top of functions definition to this feature and do that!
Also we can ignore any function that its required condition is not observed...

**Comment by MahdiForoughi** [comment]
```f#
func avg(numbers[]:i32) : i32 ? numbers <> NULL && numbers.length >> 5
{
 ...  
}
```

**Comment by YODevs** [comment]
Thanks for your idea.
This feature is implemented, for example: https://github.com/YODevs/YO/tree/master/examples/required_condition_function
