### ISSUE TITLE
Bug :: Failure to opening YOCA.exe file and run the code

### ISSUE THREAD

**Issue by shahriaarrr** [YODevs/YO#177]
After downloading the new release and running yoca.exe, this program closes quickly. Labra works and creates a new project, but in the following commands, when running, it gives the error that you see in the screenshot section.
...

**Code**
```
$ yoca vesion
$ yoca run
```

**Exception|Error|Unexpected behavior**
```
MISSING ESSENTIAL FILES : Some software files were not found.
You can reinstall the software or email us.
source : Error Code : [Err-MISSINGESSENTIALFILES-11]
*** More Detials ***
Path : D:\programming\projects\YOlang\release\ilasm.exe
                                 ***********************SNIPPT************************
Example :
Not specified
```

**Screenshots**
### yoca run command:
![image](https://user-images.githubusercontent.com/75499598/142573999-fe5b6a06-146b-46da-805e-33453a2bdfce.png)

### yoca version command:
![image](https://user-images.githubusercontent.com/75499598/142574129-0afd7271-f8e1-4414-af06-258b33a74680.png)

**Configure your system:**
 - OS: Windows 10
 - YO Version: 0.1.21

**Comment by MahdiForoughi** [comment]
Thank you! you can use **ilasm.exe** and **fusion.dll** files from last release and paste them next to your new compiler and wait for next fixes...
It might works for you just now!

**Comment by YODevs** [comment]
The final file has been updated, you can download it now.
