### ISSUE TITLE
Why Yo implemented in visual basic?

### ISSUE THREAD

**Issue by bistcuite** [YODevs/YO#181]
Hi, why Yo implemented in visual basic? C++,C# or Java is better for write a compiler/interpreter.

**Comment by YODevs** [comment]
To develop a compiler based on MSIL, it is better to use languages of the same context (various cases, including reflection , Common Data-types ,...).
Now it does not make much difference whether you write the kernel with C# or Visual Basic or F# (they work closely).
Eventually we will develop YO with YO.(Self-Hosted)

**Comment by bistcuite** [comment]
But MSIL isn't cross platform.

**Comment by YODevs** [comment]
MSIL is an intermediate language that supports .NET Core. 
The future version of YOLang supports .NET Core.
