### ISSUE TITLE
Include without strings

### ISSUE THREAD

**Issue by bistcuite** [YODevs/YO#182]
Yo currently includes libraries like this :
```
include 'ystdio'
```

I think following syntax is better and easier :
```
include ystdio
```

**Comment by YODevs** [comment]
That's a good idea!
`include` statement support for Identifiers was included in the TODO list.
https://github.com/users/YODevs/projects/2

**Comment by YODevs** [comment]
This feature was developed. Available in future version.

**Comment by bistcuite** [comment]
Thanks.
