### ISSUE TITLE
BUG :: Syntax error at token 'static'

### ISSUE THREAD

**Issue by MahdiForoughi** [YODevs/YO#184]
**Describe the bug**
I have a class that is called **static** and it should runs correctly, but the program caught an error!
**Code**
```f#
#[app::classname("static")]
```

**Exception|Error|Unexpected behavior**
```
il(6) : error : syntax error at token 'static' in: .class public auto ansi static
```

**Configure your system:**
 - OS: Windows 10
 - YO Version: 0.1.21.0

**Comment by YODevs** [comment]
Fixed.
