### ISSUE TITLE
BUG :: Problem with passing array as parameter to a method

### ISSUE THREAD

**Issue by shahriaarrr** [YODevs/YO#187]
**When we give an array as a parameter to the function, we expect the function to take the array and perform the corresponding operation. But this doesn't happen and we get the following error**
...

**Code**
```f#
#[app::classname("myapp")]
#[app::wait(true)]

include 'ystdio'

func main()
{
  let names[5] : str
  names[0] := "yolang"
  names[1] := "shahriar"
  names[2] := "Amin"
  names[3] := "mahdi"
  names[4] := "sepehr"

  print_arr(names)
}

func print_arr(arr : str[])
{
    let count : i32 = arr::length
    for(i in [0..count]){
        let name : str = arr[i]
        io::println(name)
    }
}
```

**Exception|Error|Unexpected behavior**
```
Method print_arr(...) , The parameters of the called function do not match its original function.
```

**Screenshots**
![image](https://user-images.githubusercontent.com/75499598/152112693-f0085993-917b-49dc-acc5-8360656b070c.png)

**Configure your system:**
 - OS: Windows 11
 - YO Version: 0.1.21

**Comment by YODevs** [comment]
modify code -> `func print_arr(arr[] : str)`
