### ISSUE TITLE
BUG :: Property 'length' not found.

### ISSUE THREAD

**Issue by shahriaarrr** [YODevs/YO#189]
**When we give an ```int``` array as a parameter to a method, we expect that method to take the parameter and perform operations on it. But this does not happen and we encounter the error below.**
...

**Code**
```f#
include 'ystdio'

func print_arr(arr[] : i32)
{
    let len : i32 = arr::length
    for(index in [0..len]){
        let number : i32 = arr[index]
        io::println(number)
    }
}
```

**Exception|Error|Unexpected behavior**
```
Property 'length' not found.
```

**Screenshots**
![image](https://user-images.githubusercontent.com/75499598/152207566-69a20bc1-818c-42a3-bb92-ff8817f72f65.png)

**Configure your system:**
 - OS: Windows 11
 - YO Version: 0.1.21

**Comment by YODevs** [comment]
Fixed
