### ISSUE TITLE
BUG :: Syntax error at token 'family' in: [1]  string family

### ISSUE THREAD

**Issue by MahdiForoughi** [YODevs/YO#191]
**Describe the bug**
I think this is a reserved value for compiler tokens because we caught same bugs already in #145 & #144 

**Code**
```f#
func test3()
{
  let name : str = "Mahdi"
  let family : str = "Foroughi"
  io::println("#{name}-#{family}")
}
```

**Exception|Error|Unexpected behavior**
```
il(64) : error : syntax error at token 'family' in: [1]  string family
```

**Screenshots**

**Configure your system:**
 - OS: Windows 10
 - YO Version: 0.1.22

**Comment by YODevs** [comment]
Fixed.
