### ISSUE TITLE
BUG :: Program has stopped working without any error detail

### ISSUE THREAD

**Issue by MahdiForoughi** [YODevs/YO#198]
**Describe the bug**
There is not any error detail to understanding its problem

**Code**
```f#
func main()
{
  test3()
}
func test3()
{
  let i : i32 = 18
  let xobj: obj = NULL
  xobj := [box]i
  System.Console::WriteLine(xobj)
}
```

**Exception|Error|Unexpected behavior**
```

```

**Screenshots**
![Capture](https://user-images.githubusercontent.com/46189743/154070345-0d3a20e3-708e-476e-92e4-93d2bfe8aea1.PNG)

**Configure your system:**
 - OS: Windows 10
 - YO Version: 0.1.23

**Comment by YODevs** [comment]
Fixed.
