### ISSUE TITLE
BUG :: An unknown problem in value of i32 array 

### ISSUE THREAD

**Issue by MahdiForoughi** [YODevs/YO#200]
**Describe the bug**
it returns an unknown integer value for that specified index

**Code**
```f#
func main()
{
  let arr[5] : i32
  arr[0] := 0
  arr[1] := 1
  arr[2] := 2
  arr[3] := 3
  arr[4] := 4
  for(i in [0..=4])
  {
    let item : i32 = arr[i]
    io::println(item)
  }
}

```

**Exception|Error|Unexpected behavior**
```
Output : 
0
1
2
3
-1008712432
```

**Screenshots**

**Configure your system:**
 - OS: Windows 10
 - YO Version: 0.1.22

**Comment by YODevs** [comment]
Fixed.
