### ISSUE TITLE
BUG :: Pointers do not work in .NetCore

### ISSUE THREAD

**Issue by MahdiForoughi** [YODevs/YO#205]
**Describe the bug**
When i ran **Type Casting** test codes in a new .NetCore project i caught this compilation error

**Code**
```f#
func main()
{
let i : f32 = 10.215
test4(i)
}
func test4(i:f32&)
{
  let result : str
  result := [str]i
  io::println(result)
}
```

**Exception|Error|Unexpected behavior**
```
Unhandled exception. System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at myclass.test4(Single& i)
   at myclass.main()
```

**Screenshots**

**Configure your system:**
 - OS: Windows 10
 - YO Version: 0.1.23
 - Project Framework: .NetCore

**Comment by YODevs** [comment]
Fixed.
