### ISSUE TITLE
BUG :: Instances of abstract classes cannot be created

### ISSUE THREAD

**Issue by MahdiForoughi** [YODevs/YO#206]
**Describe the bug**
I ran **constructor** test codes in a new .NetCore project and caught this error
Class **mylib** is inside of **classlibrary.yo** 
This test works with **YOAT** and .NetFramework
**Code**
```f#
func main()
{
  test1(17,18)
}
func test1(val:i32,val1:i32)
{
  let x : init mylib()
  let result : i32 = x::sum(val,val1)
  io::println("#{result}")
}

classlibrary.yo : 
public instance func sum(x:i32,y:i32):i32
{
  return [x+y]
}

public instance func sum():i32
{
  return [a+b]
}
```

**Exception|Error|Unexpected behavior**
```
Unhandled exception. System.InvalidOperationException: Instances of abstract classes cannot be created.
   at myclass.test1(Int32 val, Int32 val1)
   at myclass.main()
```

**Screenshots**

**Configure your system:**
 - OS: Windows 10
 - YO Version: 0.1.23
 - Project Framework: .NetCore

**Comment by YODevs** [comment]
Fixed .
