### ISSUE TITLE
BUG :: `Delete` method in `rds` class does not work correctly

### ISSUE THREAD

**Issue by MahdiForoughi** [YODevs/YO#207]
**Describe the bug**
I passed index 2 to **delete** function to deleting this index but it deleted every indexes that are stored before itself

**Code**
```f#
  #>YOLang Code ...
```

**Exception|Error|Unexpected behavior**
```

```

**Screenshots**
![-5796526590857951447_121](https://user-images.githubusercontent.com/46189743/155163244-95145f43-458c-495f-ae7a-722a5872c932.jpg)

**Configure your system:**
 - OS: Windows 10
 - YO Version: 0.1.22
 - Project Framework: .NetFramework

**Comment by YODevs** [comment]
Fixed.
