### ISSUE TITLE
BUG :: `to` loop and fields do not work together correctly

### ISSUE THREAD

**Issue by MahdiForoughi** [YODevs/YO#212]
**Describe the bug**
It doubles the number of output and prints 10 times instead 5 times
I tried it without fields and it worked correctly... 

**Code**
```f#
include 'ydbg'
public static let list : init yolib.list()

func main()
{
  test1(list,"1",5)
}

func test1(list:yolib.list,item:str,count:i32)
{
  to(count)
  {
    list::add(item)
  }
  dbg::print(list)
}
```

**Exception|Error|Unexpected behavior**
```
Output :: 
1
1
1
1
1
1
1
1
1
1
```

**Screenshots**

**Configure your system:**
 - OS: Windows 10
 - YO Version: 0.1.23.0
 - Project Framework: .NetFramework

**Comment by MahdiForoughi** [comment]
> ![image](https://user-images.githubusercontent.com/53114901/159285843-5c0f6e29-d947-4c53-ba64-8d499fca081b.png) No problem found, test the developing version of yoca.

So please check it out
[list_test.zip](https://github.com/YODevs/YO/files/8317879/list_test.zip)

**Comment by YODevs** [comment]
Delete line 23 inside the code.
