### ISSUE TITLE
BUG :: Method ```set_scaler_matrix()``` does not work correctly

### ISSUE THREAD

**Issue by shahriaarrr** [YODevs/YO#237]
**This function should create a scalar matrix but unfortunately this function does not work we encounter this error**
...

**Code**
```f#
let scalar : init yolib.matrix()
scalar::set_scalar_matrix(12)
dbg::print(scalar)
```

**Exception|Error|Unexpected behavior**
```
RUNTIME ERROR : An unknown error occurred while running.
source : Error Code : [Err-RUNTIMEERROR-3]
*** More Detials ***
Argument 'Number' must be greater or equal to zero.
                                 ***********************SNIPPET************************                                 
Example :
Not specified
```

**Configure your system:**
 - OS: [Windows 11]
 - YO Version: [0.1.24 ]
 - Project Framework: [.NetFramework]

**Comment by YODevs** [comment]
This issue has been resolved(#225), but you can use the following code to fix this bug immediately:
```f#
  let scalar : init yolib.matrix(3,3)
  scalar::set_scalar_matrix(12)
  dbg::print(scalar)
```
