### ISSUE TITLE
BUG :: YOAT can not reads matrix form from output.txt file

### ISSUE THREAD

**Issue by MahdiForoughi** [YODevs/YO#238]
**Describe the bug**
This is a ctest project , there is no error or exception , but YOAT can not reads its output form specific file and match it with original output that compiler shows
Project is attached...

**Code**

**Exception|Error|Unexpected behavior**

**Screenshots**

**Configure your system:**
 - OS: Windows10
 - YO Version: 0.1.24.0
[matrix_test.zip](https://github.com/YODevs/YO/files/8449729/matrix_test.zip)

 - Project Framework: .NetFramework

**Comment by YODevs** [comment]
[output.txt](https://github.com/YODevs/YO/files/8463041/output.txt)

Observe the distances after the matrix numbers.
