### ISSUE TITLE
Feature :: Create an identify matrix

### ISSUE THREAD

**Issue by MahdiForoughi** [YODevs/YO#244]
**Description**

...

**Sample code**

```f#
let mt : yolib.matrix = yolib.matrix::identify(4)

#- 
Result : 
1    0    0    0
0    1    0    0
0    0    1    0
0    0    0    1
-#
```

**References**

References needed to study and obtain prerequisites for the feature.

**Comment by YODevs** [comment]
![image](https://user-images.githubusercontent.com/53114901/165071825-4c783d7c-629c-441b-994c-ea48b797297d.png)
```f#
 let mt : yolib.matrix = yolib.matrix::unit_matrix(8)
 let f : init yolib.dataframe()
 f::show(mt)
 ```
