### ISSUE TITLE
BUG :: There is no duplicate declaration error

### ISSUE THREAD

**Issue by MahdiForoughi** [YODevs/YO#255]
**Describe the bug**

**Code**
```f#
public static let x : i32 = 20

func main()
{
  let x : i32 = 10
  io::println(x)
}
#> Output : 10
```

**Screenshots**

**Configure your system:**
 - OS: Windows 10
 - YO Version: 0.1.24
 - Project Framework: .NetFramework

**Comment by YODevs** [comment]
Fixed.
