### ISSUE TITLE
BUG :: Unable to using any method of validator class

### ISSUE THREAD

**Issue by MahdiForoughi** [YODevs/YO#295]
[validating.zip](https://github.com/YODevs/YO/files/11497673/validating.zip)
**Describe the bug**
...

**Code**
```f#
func main()
{
  let b : bool = yolib.validating::is_equals("mahdi", "mehdi",true)
  io::println("#{b}")
}

```

**Exception|Error|Unexpected behavior**
```
Unhandled Exception: System.MissingMethodException: Method not found: 'Boolean YOLIB.validating.is_equals(System.String, System.String, Boolean)'.
   at myapp.main()

```

**Screenshots**

**Configure your system:**
 - OS: Windows 10
 - YO Version: 0.1.26.0 
 - Project Framework: .NetFramework

**Comment by YODevs** [comment]
A new error was defined for this type of problem.
